
version: 2

sources:
  - name: prod
    database: bronze_prod
    schema: raw
    tables:
      - name: policy
      - name: address
      - name: address_type
      - name: contact
      - name: contents
      - name: coverage
      - name: coverage_type
      - name: occupancy
      - name: party
      - name: party_policy_association
      - name: premium_detail
      - name: property
      - name: transaction
      - name: property_occupation_type
      - name: property_type
      - name: roof_material_type
      - name: transaction_status_type
      - name: transaction_type
      - name: wall_material_type

models:
    - name: policy
      columns:
        - name: brand
          tests:
          - is_valid_brand

