
version: 2

sources:
  - name: prod
    database: bronze_prod
    schema: raw
    tables:
      - name: policy
      - name: address

models:
    - name: policy
      columns:
        - name: brand
          tests:
          - is_valid_brand

