
version: 2

sources:
  - name: prod
    database: bronze_prod
    schema: raw
    tables:
      - name: policy

models:
    - name: policy
      columns:
        - name: policy_id
          tests:
            - unique
            - not_null
        - name: modified
          tests:
          - unique
          - not_null
        - name: brand
          tests:
          - is_valid_brand

