dbt_silver:
  target: dev
  outputs:
    dev:
      account: abnyhbb-fm74053
      database: silver_dev
      password: "{{ env_var('password') }}" 
      role: ACCOUNTADMIN
      schema: clean
      threads: 12
      type: snowflake
      user: realitybytez
      warehouse: portfolio
    prod:
      account: abnyhbb-fm74053
      database: silver_prod
      password: "{{ env_var('password') }}"
      role: ACCOUNTADMIN
      schema: clean
      threads: 12
      type: snowflake
      user: realitybytez
      warehouse: portfolio
