name: dbt-silver-ci

on:
  push:
    paths:
      - 'src/portfolio/silver/models/silver/clean/policy_forge/**'
      
  pull_request:
    paths:
      - 'src/portfolio/silver/models/silver/clean/policy_forge/**'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      DBT_PASSWORD: ${{secrets.DBT_PASSWORD}}
    steps:
      - name: "Check if password available"
        if: ${{ env.DBT_PASSWORD == '' }}
        run: |
          echo "DBT password unavilable"
      
      - name: "password length"
        run: |
          echo ${#DBT_PASSWORD}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Fetch dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/portfolio/requirements.txt

      - name: Lint Silver (Clean)
        run: |
          sqlfluff lint src/portfolio/silver/models/silver/clean/policy_forge --dialect snowflake

      - name: DBT Silver Dev Build
        run: |
          cd src/portfolio/silver
          dbt run --target dev --profiles-dir ./

      - name: DBT Silver Dev Test
        run: |
          cd src/portfolio/silver
          dbt test --target dev --profiles-dir ./
